binop_separator = "Front"
comment_width = 80
doc_comment_code_block_width = 80
edition = "2021"
empty_item_single_line = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Upper"
imports_granularity = "Crate"
imports_layout = "Vertical"
indent_style = "Visual"
match_block_trailing_comma = true
max_width = 80
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
single_line_if_else_max_width = 0
struct_field_align_threshold = 20
struct_lit_single_line = false
unstable_features = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
